### ISSUE TITLE
Date at top

### ISSUE THREAD

**Issue by chilthekite** [UlsterPublishing/BrowseableListings#2]
Wasn't in the original request... but looking at it, I think it would be nice to have the date at the top of the listings in plain text, just under links. It seems a little abrupt going from the links to the listings. Maybe just wrap it in an h2. 
![browseable2](https://cloud.githubusercontent.com/assets/21107243/17956583/0951fc34-6a59-11e6-8b58-f6d91a335271.jpg)

**Comment by chriscapaci** [comment]
Impossible

**Comment by chilthekite** [comment]
dang
