### ISSUE TITLE
Include premier listings

### ISSUE THREAD

**Issue by chilthekite** [UlsterPublishing/BrowseableListings#3]
I forgot --- they absolutely LOVE premier listings, and every time I think I'm done with something they ask for it to be added. Premier listings are horrible, horrible line ads masquerading as events that bring around $200 each week total and take up about 90 percent our time. The premier listings are posts, not events, with the category "premier". So the query is something like 

```
'post_type'=>'post',
'post_status'=>'publish',
'category_name' => 'premier'
```

The output would be slightly difference since there's no date/time. It's just the title (as a link) and the content. 

On the staging site premier listings are all on the homepage because they're the only posts, so you can see what's there. In general there's around 20-30 listings each week so increasing load time not an issue.

**Comment by chriscapaci** [comment]
"Include premier listings" where? On the browseable page? I see them on the staging site all on their own when I click on the premier listing image/link, but this description doesn't really say waht you want done. Explain please.
